### ISSUE TITLE
Prevent the use of special layer names such as "build", "launch" or "store"

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#101]
In [Buildpack API 0.6](https://github.com/buildpacks/spec/releases/tag/buildpack%2Fv0.6), attempts to create layers with a name of "build", "launch" or "store" are forbidden by the spec, since those layer names conflict with the layer metadata files (eg `build.toml`).

Whilst using those names will result in failures during the build, it would be helpful for libcnb to validate the layer names itself and fail early if those reserved names are used.

This issue is not in the Buildpack API 0.6 milestone, since this is more of a nice-to-have that's not required for 0.6 support.

**Comment by schneems** [comment]
I looked into it and we don't have one abstraction for layer names. Rather every place we're looking for a layer name we're accepting an `AsRef<str>`. 

Thinking aloud a bit, It looks like the options would be:

A) Check `layer_name` everywhere it's present, there's a bunch of usage in `layer_lifecycle.rs` and `build.rs`. For example:
  - https://github.com/Malax/libcnb.rs/blob/05836128f73de9ae67e78a1c68f28165d1d2945c/src/build.rs#L28
  - https://github.com/Malax/libcnb.rs/blob/6a94d587814bce9f2a2f411cd655c2c09063a033/src/layer_lifecycle.rs#L163

Not very DRY, might be prone to logic leakage if new logic is implemented without the checks. A lot of duplicate checking. No build time errors.

B) Be strategic and only check/error on `layer_name` in some locations (but not all)

Less duplicate checking. Not very DRY, might be prone to logic leakage if new logic is implemented without the checks. No build-time errors.

C) Introduce a `LayerName` type with a constructor that forces these constraints.  

The most work, but probably the most verifiably correct thing to do. We could perhaps make this better by implementing automatic conversions from string and &str to that type. Something like this conversion I used in another PR:

```rs
#[derive(Clone)]
pub enum BuildpackDescriptorArg<BM: Clone> {
    File(PathBuf),
    String(String),
    BuildpackToml(BuildpackToml<BM>),
    None,
}

impl<BM: Clone> From<PathBuf> for BuildpackDescriptorArg<BM> {
    fn from(value: PathBuf) -> Self {
        BuildpackDescriptorArg::File(value)
    }
}
```

Actually, now that I'm looking at it, I don't know if it's possible to implement `From` that may return an error. There is try-from/try-into https://doc.rust-lang.org/std/convert/trait.TryFrom.html which is what I think we would need.

This approach still relies on us remembering to use this type every time we want to work with a layer name. It would require the buildpack author to add a `try_into()?` call to their string. Which also as I'm thinking on it, would be checked at runtime and not at compile time. I don't think we can get a "build time error" for this detection.

D) Do nothing and let the CNB lifecycle raise an error

Pack would still raise an error, which might be enough.

There is benefit in erroring outside of `pack` for anyone who doesn't jump through the hoops of implementing integration tests even if it's "at runtime". But that benefit is only realized by someone who would be exercising the interface where the checking occurs.


D) A macro?

Maybe if we had something like `layer!("build")` we could get it to perform that check before runtime (I think). Seems a little odd though. I'm not sure if that's a normal use of macros or if that's a weird abuse.

Also, i double-checked, and macros may compile at build time, but their code doesn't execute until you run it. https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=59828a5acb2c6ab283f2d82501cb25bc

So it doesn't solve anything. I just don't think a build time compile error is possible for this https://twitter.com/schneems/status/1450910021533929473

**Comment by edmorley** [comment]
@schneems Thank you for writing up the options! I guess one option is to do (D) for now, and see how we feel about this later? It needn't block the 0.6 release (I didn't add it to the milestone), so there isn't too much rush :-)

**Comment by edmorley** [comment]
@Malax Should we just wontfix this, given pack will enforce it?

**Comment by Malax** [comment]
> So it doesn't solve anything. I just don't think a build time compile error is possible for this https://twitter.com/schneems/status/1450910021533929473

A compile time error _is possible_ by using a proc macro. With the changes in #162, we're in a good spot to solve this generically for all newtypes. I'm working on it.
