### ISSUE TITLE
Rename `TargetLifecycle`

### ISSUE THREAD

**Issue by schneems** [Malax/libcnb.rs#170]
Discussed in https://github.com/Malax/libcnb.rs/pull/144/files#r751525550

https://github.com/Malax/libcnb.rs/blob/b2ba884a37dd58ce010eb01a66748cbfe5bd6c20/libcnb/src/layer_env.rs#L424-L431

Maybe we want to consider renaming this. To me the lifecycle is the thing we're currently in (the layer/lifecycle). So I was reading this code and thinking "this env will apply to all layers" when what this really means is "this env applies to all layer types (build, cache, launch)". 

Above we call the struct `LayerTypes` so perhaps `TargetLayerTypes::All`. The "target" term is also a little ambiguous. Maybe `ApplyToLayerType::All` or `OnLayerType::All`. WDYT?

**Comment by edmorley** [comment]
I agree `TargetLifecycle` is ambiguous :-)

> what this really means is "this env applies to all layer types (build, cache, launch)".

So I think the behaviour controlled by `TargetLifecycle` is actually different to that. If in one buildpack I set an env var using `TargetLifecycle::Build` (which causes it to be written to `<layers>/<layer>/env.build/` by libcnb), it means it's available at build time for **all** layers of later buildpacks, even if those later layers are say only `launch=true`. So it's not targetting later `LayerTypes`, but instead whether the env var should be exposed to {later buildpacks only, launch only, everywhere).

Looking at the CNB spec for inspiration, I see "lifecycle phases" being used to describe detect / build, and even launching. eg:
https://github.com/buildpacks/spec/blob/main/buildpack.md#provided-by-the-buildpacks
https://github.com/buildpacks/spec/blob/main/platform.md#lifecycle-interface

@schneems @Malax What do you think about `TargetPhase` or `TargetLifecyclePhase`?

**Comment by edmorley** [comment]
> What do you think about `TargetPhase` or `TargetLifecyclePhase`

So I was thinking about this some more - one problem with "phase" is that the enum contains `Process` as a variant (not just All/Build/Launch), and process isn't really a phase, it's a subset of the launch phase.

The current naming also doesn't mention env vars at all, when they are at the centre of understanding this type.

This led me to names like:
`EnvTarget`
`EnvVarTarget`

Though IMO "target" is not as clear as it could be. I was thinking we might be better using "scope" instead?

eg:
`EnvVarScope::All`
`EnvVarScope::Build`
`EnvVarScope::Launch`
`EnvVarScope::Process`

@hone @Malax @schneems Thoughts?
