### ISSUE TITLE
Should stack mixin naming be enforced?

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#181]
Currently a stack's `mixins` are represented as `Vec<String>`:
https://github.com/Malax/libcnb.rs/blob/2f57cd18beff95a52fd85229823e0c8dc05892ce/libcnb-data/src/buildpack.rs#L81

The CNB spec says:

> A mixin name MUST only be defined by the author of its corresponding stack. A mixin name MUST always be used to specify the same set of changes. A mixin name MUST only contain a : character as part of an optional stage specifier.
> 
> A mixin prefixed with the build: stage specifier only affects the build image and does not need to be specified on the run image. A mixin prefixed with the run: stage specifier only affects the run image and does not need to be specified on the build image. A mixin WITHOUT a build: or run: prefix affects both the build and the run images.
> -- https://github.com/buildpacks/spec/blob/buildpack/0.6/platform.md#mixins

There is also a section in the buildpack API spec, however it's not very helpful:
https://github.com/buildpacks/spec/blob/buildpack/0.7/buildpack.md#mixin-satisfaction

The wording above does not state this explicitly, but the implication is that at present, the only accepted "stage specifiers" are `build` and `run`.

With that interpretation, the mixin name could be validated with a newtype regex of `r"^((build|run):)?.+$"`.

However is this something we still want to do, given:
(a) the lack of specifics in the spec,
(b) the fact that the spec suggests the stack creator is in control over the mixins names, rather than the buildpack (so validating the choice of name in the buildpack seems less useful)

..?

**Comment by Malax** [comment]
I agree with the usefulness of validation when the mixin names are controlled by the stack creator. In addition, the concept of stacks (and mixins) will go away soon so we shouldn't put too much effort into it.

`r"^((build|run):)?.+$"` seems fine to me at this point.

**Comment by edmorley** [comment]
I'm not sure I follow. It seems you are both agreeing it's not useful and so maybe not worth it, but also saying we should do it? (I'm happy either way fwiw)

**Comment by edmorley** [comment]
Also, I got the regex wrong, it would need to be `r"^((build|run):)?[^:]+$"`.

However trying that, no error is surfaced in the newly added `stacks_invalid_mixin_name` test? Seems like an issue with the newtype helpers and serde deserialize? eg:
https://github.com/Malax/libcnb.rs/compare/edmorley/StackMixin
https://github.com/Malax/libcnb.rs/runs/4299068994?check_suite_focus=true#step:5:89

**Comment by edmorley** [comment]
I don't think this is worth doing, given:

> (a) the lack of specifics in the spec,
> (b) the fact that the spec suggests the stack creator is in control over the mixins names, rather than the buildpack (so validating the choice of name in the buildpack seems less useful)

...

> In addition, the concept of stacks (and mixins) will go away soon so we shouldn't put too much effort into it.
