### ISSUE TITLE
Unable to `.join()` newtype macro types

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#182]
A `Vec<String>` (which is what `mixins` currently is) can be joined like so:
https://github.com/Malax/libcnb.rs/blob/2f57cd18beff95a52fd85229823e0c8dc05892ce/libcnb-data/src/buildpack.rs#L102

However if the `Vec<String>` is converted to `Vec<StackMixin>`, with `StackMixin` having been created using the `libcnb_newtype` macro, a trait bounds not satisfied error is generated when `.join()` is used.

For example:

```rust
    let mixins = vec![stack_mixin!("a"), stack_mixin!("b")];
    println!("mixins: {}", mixins.join(", "));
```

```
error[E0599]: the method `join` exists for struct `std::vec::Vec<buildpack::StackMixin>`, but its trait bounds were not satisfied
   --> libcnb-data/src/buildpack.rs:319:35
    |
319 |     println!("mixins: {}", mixins.join(", "));
    |                                   ^^^^ method cannot be called on `std::vec::Vec<buildpack::StackMixin>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<[buildpack::StackMixin] as std::slice::Join<_>>::Output = _`

For more information about this error, try `rustc --explain E0599`.
```

I presume we're missing a trait implementation on `libcnb_newtype` that would allow this?

**Comment by edmorley** [comment]
I found https://github.com/rust-lang/rust/issues/82910#issuecomment-792995807 and tried adding this, which seemed to work, but no idea if it's the correct approach:

```rust
        impl ::std::borrow::Borrow<str> for $name {
            fn borrow(&self) -> &str {
                &self.0[..]
            }
        }
```

**Comment by Malax** [comment]
We already have `Borrow<String>` for our newtypes:
```rust
impl ::std::borrow::Borrow<String> for $name {
    fn borrow(&self) -> &String {
        &self.0
    }
}
```

So I'd assume adding `Borrow<str>` is not too bad? :)

**Comment by edmorley** [comment]
@Malax With #181 wontfix, the need for this is less. I guess it depends on whether we see ourselves joining lists of other newtypes (eg process names) in log output etc?
