### ISSUE TITLE
Buildpack `version` validation permits values not allowed by the spec

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#239]
The version of a buildpack is specified by the `version` field in `buildpack.toml` like so:

```toml
api = "0.6"

[buildpack]
id = "foo/bar"
version = "0.0.1"

[[stacks]]
id = "*"
```

The CNB spec says:

> The buildpack version:
>    MUST be in the form `<X>.<Y>.<Z>` where `X`, `Y`, and `Z` are non-negative integers and must not contain leading zeros.
>     -  Each element MUST increase numerically.
>     -  Buildpack authors will define what changes will increment `X`, `Y`, and `Z`.

However currently the version is implemented using the [semver](https://crates.io/crates/semver) crate:
https://github.com/Malax/libcnb.rs/blob/6cba43aa9fa70fb28b5ef5ff126987df5f3fad95/libcnb-data/src/buildpack/mod.rs#L61

...which permits any allowed semver version - including those that have `-foo` and `+foo` suffixes (which are not allowed in buildpack versions):

```
<valid semver> ::= <version core>
                 | <version core> "-" <pre-release>
                 | <version core> "+" <build>
                 | <version core> "-" <pre-release> "+" <build>

<version core> ::= <major> "." <minor> "." <patch>
```

(from https://semver.org)

We should switch to our own parsing/validation to ensure only versions of form `X.Y.Z` are permitted.

This came up in a recent JVM buildpack PR, where a buildpack was given an invalid version but was only found when run with pack in CI.

**Comment by edmorley** [comment]
Though that said, `pack build` and `pack buildpack package` both quite happily work with a buildpack version of `00.0.1.1-dev` which violates every single rule:

```
$ pack buildpack inspect test-buildpack
Inspecting buildpack: test-buildpack

LOCAL IMAGE:

Stacks:
  ID: io.buildpacks.samples.stacks.bionic
    Mixins:
      (omitted)
  ID: io.buildpacks.samples.stacks.alpine
    Mixins:
      (omitted)
  ID: io.buildpacks.stacks.bionic
    Mixins:
      (omitted)

Buildpacks:
  ID                         NAME                         VERSION             HOMEPAGE
  samples/hello-world        Hello World Buildpack        00.0.1.1-dev        https://github.com/buildpacks/samples/tree/main/buildpacks/hello-world

Detection Order:
 └ Group #1:
    └ samples/hello-world@00.0.1.1-dev
```

**Comment by edmorley** [comment]
So I think it would be good to be able to drop the `semver` crate dependency, and also the misleading `semver::Version` struct, since it has pre-release fields etc that are not accurately modelling the data.

This can either be implemented as split+parse (like for buildpack API), or else as regex. I was hoping to use the former, but it accepts version components with leading zeros, which the spec forbids (though Pack accepts, so 🤷). For regex, libcnb-data already has a dependency on a regex crate, so it wouldn't mean another dependency at least.

**Comment by Malax** [comment]
I encountered this issue recently as well. Thanks for writing this issue @edmorley!

Dropping `semver` makes sense to me. Besides being incorrect, we don't need SemVer semantics at all here. The fact that pack doesn't enforce the spec shouldn't be much of a consideration for libcnb.

I'd go with the regex approach for maximum correctness here.
