### ISSUE TITLE
Scope not accessible in libcnb 0.4.0

### ISSUE THREAD

**Issue by schneems** [Malax/libcnb.rs#268]
The existing ruby example works, but if you change the toml to point at the released version instead of what's on disk:

```
$ cat Cargo.toml
[package]
name = "example-02-ruby-sample"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
flate2 = "1"
ureq = "2.2.1"
sha2 = "0.10"
tar = "0.4"
toml = "0.5"
tempfile = "3"
libcnb = "0.4.0"
serde = "1.0.126"
```

You get an error:

```
$ cargo build
   Compiling libcnb-data v0.3.0
   Compiling libcnb v0.4.0
   Compiling example-02-ruby-sample v0.1.0 (/Users/rschneeman/Documents/projects/work/libcnb.rs/examples/example-02-ruby-sample)
error[E0432]: unresolved import `libcnb::layer_env::Scope`
 --> examples/example-02-ruby-sample/src/main.rs:7:5
  |
7 | use libcnb::layer_env::Scope;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `Scope` in `layer_env`

error[E0432]: unresolved import `libcnb::layer_env::Scope`
  --> examples/example-02-ruby-sample/src/layers/ruby.rs:12:57
   |
12 | use libcnb::layer_env::{LayerEnv, ModificationBehavior, Scope};
   |                                                         ^^^^^ no `Scope` in `layer_env`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `example-02-ruby-sample` due to 2 previous errors
```

**Comment by edmorley** [comment]
This is expected - `TargetLifecycle` was renamed to `Scope` in #257, which has not yet been released.

You either need to use libcnb from `main` with the examples from `main`, or `libcnb` 0.4.0 with the examples from `0.4.0`:
https://github.com/Malax/libcnb.rs/tree/v0.4.0/examples/example-02-ruby-sample

Obviously not ideal that the examples from `main` don't work with the latest published release as-is, but its the tradeoff for having the example exercise our latest code. In general once the number of libcnb breaking changes settles down, this situation shouldn't arise very often :-)

**Comment by schneems** [comment]
Thanks josh and I figured this out almost the exact same time. Is there a milestone for 0.4.1 or is there anything preventing releasing what's on main?

**Comment by edmorley** [comment]
#257 landed yesterday (you were one of the reviewers requested fwiw), so it's not been waiting long.

I think we're waiting on 1-2 more PRs that are breaking (eg #243 and #265), but otherwise were wanting to release soon.
