### ISSUE TITLE
Move libcnb-test integration tests from the CI `test` job to the `integration` job

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#301]
Currently in #277, the libcnb-test integration tests (both those in the libcnb-test crate, and the examples crates) are run in the CI `test` job, rather than the `integration` job.

This means that the `test` job (a) has to spend time installing/configuring the musl and Pack related parts of CI setup (which aren't needed for the unit tests, (b) means the time spent running the tests after setup is also much longer.

For example, before #277 the warm CI Rust cache durations were as follows:
- `lint`: 30s
- `test`: 45s
- `integration`: 55s

And after:
- `lint`: 45s
- `test`: 2m45s
- `integration`: 1m05s

There are a few ways to resolve this:
1. Passing path globs or `--lib` to `cargo test`, so it only runs the unit tests in the `test` CI job (and then adjusting the `integration` job accordingly). ie: An opt out approach.
2. Putting the integration tests behind a `#[cfg(feature = "integration")]` type flag, and adjusting the CI config accordingly. ie: An opt-in approach.

The approach we use for this repository will also likely be the approach that others copy for their repository, so worth thinking a bit more carefully about it as a result.

Split out of:
https://github.com/Malax/libcnb.rs/pull/277#discussion_r793782415

**Comment by schneems** [comment]
I wanted to share some of my context. In ruby land I've found two strategies that help with "my tests are taking too long". I separate out tests that are short running into their own directory, so I can run them all at once. Another feature I do (sometimes) is to tag certain tests as "slow" then I can run the fast ones first and if they fail stop there, if they pass continue to run everything:

```
function fast() {
  bundle exec rspec --tag \~slow $@ && bundle exec rspec --tag slow $@
}
```

I understand the landscape is different in Rust, but that's a pattern that has worked well for me.

Comments on this issue directly: I have a desire to be able to run unit tests without invoking integration tests for fast cycle time in development of individual features. I currently don't run my hatchet tests locally while I develop (though that might change with switching over to pack). If I take my current development patterns and apply them to this issue I think I would like `cargo test` to be fast and when I want to run the full suite, let me access it as an opt-in. 

All that is to say: I think I prefer a feature-flagged approach to exposing and isolating integration tests from other tests.

**Comment by edmorley** [comment]
@schneems I also would prefer an opt-in approach, so that the common case of "run all my unit tests quickly" doesn't require more typing.

A third option (which also allows opt-in, like option 2 in the OP above) is to put the `#[ignore]` attribute on all of our integration tests. This means that they are skipped during a normal `cargo test`, however can be run by using `cargo test -- --ignored` (this runs only the ignored tests, not all tests).

There's more on the `#[ignore]` attribute here:
https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested

The differences between `#[ignore]` and `#[cfg(feature = "integration")]` are:
- With ignore, the integration tests are still compiled (just not run), whereas with a feature, they wouldn't be compiled. In reality this probably doesn't make too much difference, because IDEs can be configured to lint using `--all-targets` (which will confirm the integration tests compile even without running `cargo test`).
- `ignore` can't be used as a module-wide attribute (`#![...]`) so has to be added to every integration test function, whereas `cfg` can be added to the top of the integration test module.
- with ignore, the skipped tests show up in the standard `cargo test` output (making it clearer that some tests were skipped), whereas with a feature, they won't (meaning users may not realise there are extra tests until they push and CI fails).
- the syntax for running ignored tests is `cargo test -- --ignored` compared to `cargo test --all-features` when using features. If the extra `--` is omitted from the ignored version, the error message isn't very clear (perhaps we could report this upstream). That said, `--all-features` is also a bit of a misnomer, since running additional tests isn't really a "feature".

I could go either way between ignore and a feature flag -- perhaps very marginally leaning towards `ignore`? 

@schneems @Malax @hone thoughts?

Whichever we pick, I intend for us to update the examples/tests/CI config in this repo to use it - both so this project can benefit, but also to serve as a best practice for others to follow.

**Comment by edmorley** [comment]
Example output when using `ignore` and running just `cargo test`:

<img width="861" alt="screenshot of cargo test output" src="https://user-images.githubusercontent.com/501702/153724105-0a4689b8-583f-4894-9974-3afd0234c5bb.png">

**Comment by edmorley** [comment]
I've opened #316 using the `#[ignore]` attribute approach, to make the proposal easier to visualise/discuss.
