### ISSUE TITLE
Enable missing lints in examples and integration tests

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#302]
The Rust attributes we use to enable the pedantic/unused_crate_dependency lints must be added to every `main.rs` and `lib.rs` in order that they be enabled for the binary/library. (At least until Cargo/Clippy offers a way to specify crate/repo wide lint options.)

These annotations are currently missing from the examples under `examples/`.

In addition, it seems that since integration tests result in a separate binary, we must add them there too. Doing this would have caught the fact that one of the integration tests returned a `Result` but yet only ever returned `Ok` (due to unwrapping all errors):
https://github.com/Malax/libcnb.rs/pull/277#discussion_r796818127

**Comment by Malax** [comment]
Ugh, I _really_ want Cargo workspace-wide Clippy settings - this is so annoying TBH. :(
