### ISSUE TITLE
Move the library part of `libcnb-cargo` to a separate crate

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#332]
Currently the `libcnb-cargo` crate is both a binary (that powers the cargo plugin), and a library (that's used by both the binary, and separately by `libcnb-test` and any other external consumers).

End-user projects will have `libcnb-test` in their `dev-dependencies`, which itself depends upon the library part of `libcnb-cargo`. Whilst these projects will also use the CLI part, they do so by `cargo install`ing it, which doesn't use the project's `target/` directory.

As such, by having both the CLI and library in the same crate, we make these projects unnecessarily compile the CLI-specific dependencies, such as `clap`, `pathdiff`, `size_format` and `stderrlog` (and all of their transitive dependencies). (Which on `main` is currently 23 extra dependencies; this will go up after #329 since Clap v3 has a few more deps.)

To prevent this, we could move the library parts of `libcnb-cargo` to another crate. Then `libcnb-cargo` would contain only a binary (the cargo plugin), and both it and `libcnb-test` would depend on the new crate.

In addition to reducing the dependency tree, such a move would make it easier to keep track of breaking changes/writing the changelog for the library vs the binary parts of `libcnb-cargo` (for example we've accidentally released breaking library changes in a patch release of `libcnb-cargo` before, because it wasn't a breaking change for the CLI).

Potential names for this crate:
- `libcnb-build`
- `libcnb-compile`
- `libcnb-packaging`
- `libcnb-package`

Note: I've intentionally not considered a `libcnb-common` or similar type name, since the crate will be a development only dependency, so won't want to be in the same crate as non-dev dependencies.

@Malax @hone Thoughts?

**Comment by hone** [comment]
I assume this isn't a high priority, but the reasoning is sound. `libcnb-package` would be my preference on that bikeshed.

**Comment by edmorley** [comment]
Yeah not super high priority. I've just been getting a lot of ICEs using Rust beta this week due to bugs with incremental compilation (they are now going to disable incremental compilation when 1.59 hits stable later this week), that have required blowing away `target/` 5-10 times a day, which has been exacerbating slow compile times.

**Comment by edmorley** [comment]
I also prefer `libcnb-package` fwiw :-)
