### ISSUE TITLE
`BuildPlan` 's `or` field should probably be public

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#351]
`BuildPlan` has public `requires` and `provides` fields, but a private `or` field:
https://github.com/Malax/libcnb.rs/blob/0ca9e3ed828f174633367c748c33164331513cf9/libcnb-data/src/build_plan.rs#L7-L14

We should probably make `or` public too, given all three have equal standing in the build plan:
https://github.com/buildpacks/spec/blob/main/buildpack.md#build-plan-toml

**Comment by hone** [comment]
This is a blocking issue for me.
