### ISSUE TITLE
`MultipleBinTargets` found when using workspaces and exec.d

### ISSUE THREAD

**Issue by joshwlewis** [Malax/libcnb.rs#357]
My project looks like this:

```
- Cargo.toml (with workspaces)
- buildpacks
  - bar
  - foo
    - src
      - main.rs
      - bin
        - exec_d.rs
```

Whenever I attempt to run `cargo libcnb package` I get the error `MultipleBinTargetsFound`. I believe this happens because it's finding both my `main.rs` and my `exec_d.rs`, but neither of them match the cargo root name (which is probably the workspace root, not the buildpack root?) here:

https://github.com/Malax/libcnb.rs/blob/4675daf0faa5d04166ef3715ead16e7be127ccad/libcnb-cargo/src/config.rs#L25-L27

**Comment by edmorley** [comment]
The exec.d feature hasn't yet been released:
https://github.com/Malax/libcnb.rs/blob/main/libcnb-cargo/CHANGELOG.md#unreleased
https://github.com/Malax/libcnb.rs/blob/main/libcnb/CHANGELOG.md#unreleased

If you would like to use it in the meantime, add `path = "..."` annotations to your `Cargo.toml` files to point at a local checkout of libcnb.rs + install the development version of `libcnb-cargo` using `cargo install --path <path to libcnb.rs>/libcnb-cargo/`.

**Comment by joshwlewis** [comment]
> The exec.d feature hasn't yet been released

I know, but I'm using it anyway with `libcnb = { git = "https://github.com/Malax/libcnb.rs" }`.

I'm about to drop cargo workspaces, so if I don't file a bug now, I'll probably forget the issue.

**Comment by edmorley** [comment]
This isn't related to workspaces.

Your libcnb-cargo version does not support exec.d. Using `libcnb = { git = "https://github.com/Malax/libcnb.rs" }` doesn't change the 1libcnb-cargo` version you have installed globally.

`cargo install` is like `npm install --global`.

**Comment by edmorley** [comment]
Or to put it another way, even when there are new libcnb/... crate versions released, updating your `Cargo.toml` files to reference those files won't be enough on its own. You'll also then need to `cargo install libcnb-cargo` to install the latest tool globally.

**Comment by joshwlewis** [comment]
Yeah, understood.

I'm seeing this with `cargo test` as well. But that may be because I'm using the latest release of libcnb-test.

**Comment by edmorley** [comment]
So currently `cargo libcnb package` has to be run from the specific crate - it can't be run from the workspace root. Supporting that is #215.

The latest `libcnb-test` on `main` supports workspaces, since it works with this repository, which uses workspaces.

**Comment by joshwlewis** [comment]
Ok, gotcha. It seems to be working now using unreleased `libcnb-cargo` and `libcnb-test`.

**Comment by edmorley** [comment]
I've filed #358 for improving the UX when mismatched versions are used together :-)
