### ISSUE TITLE
Clean up WIP branches

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#47]
There are a few WIP branches on this repo - it would be good to either delete them (if no longer wanted) or finish them up.

These two seem redundant after #28:
https://github.com/Malax/libcnb.rs/compare/build_context_new?expand=1
https://github.com/Malax/libcnb.rs/compare/malax/typed-layer-metadata-proto?expand=1

This one may still be relevant:
https://github.com/Malax/libcnb.rs/compare/buildpack_toml_serialize?expand=1

**Comment by Malax** [comment]
I removed mine.

**Comment by edmorley** [comment]
@hone Could you see if these branches of yours are still needed? :-)
https://github.com/Malax/libcnb.rs/compare/build_context_new?expand=1
https://github.com/Malax/libcnb.rs/compare/buildpack_toml_serialize?expand=1

**Comment by hone** [comment]
yeah, I think the buildpack toml serialize is the only one I want to keep. Manuel kind of broke the world with 0.2.0. :|
