### ISSUE TITLE
Consider enabling some/most of Clippy's pedantic lints

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#66]
Clippy's lints are grouped into various categories, one of which is `clippy::pedantic`, which is not enabled by default.

Depending on the outcome of the GitHub issues filed for fixing some of the warnings from these pedantic lints (see https://github.com/Malax/libcnb.rs/issues?q=is%3Aissue+clippy+pedantic), we may want to enable some/most of them, to prevent regressions in the future.

Whilst we want to avoid enabling annoying (or false-positive-prone) lints, given that this is a new project (so we don't have thousands of line of Rust to fix) and as a team we're new to the language (so could do with guidance when it comes to writing idiomatic Rust), it's likely worth us taking advantage of at least some of the pedantic lints.

Cross-ref heroku/libherokubuildpack#18.

**Comment by Malax** [comment]
I looked at some of the issues you created after running `clippy::pedantic` and most of them are useful I think. I have no idea about the false-positive rate, but at least for libcnb, I could not see any here. I'll work through all of them to get a better feel, but at this point I'm leaning towards enabling pedantic lints.

**Comment by edmorley** [comment]
If we were to enable them (I'm leaning towards thinking it's worth us doing so) we can always do so with the understanding that it's fine (and expected) to disable any individual lints within `clippy::pedantic` that start being annoying in the future.
