### ISSUE TITLE
Reduce cognitive overhead of `LayerLifecycle`'s large number of generic arguments

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#68]
This is a review comment split out of https://github.com/Malax/libcnb.rs/pull/28#pullrequestreview-705465664.

If this suggestion ends up being wontfix we can always close this issue out, however I didn't want it to get lost given that the PR was already merged :-)

> * The number of generic arguments for `LayerLifecycle`. There's 5 and I think it's a lot of cognitive overhead there. I wonder if we can use things like associated types to make this easier.
> -- @hone

**Comment by Malax** [comment]
This has been addressed with #129.
