### ISSUE TITLE
Loosen trait restrictions on the Error returned by closures added in #28

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#69]
This is a review comment split out of https://github.com/Malax/libcnb.rs/pull/28#pullrequestreview-705465664.

If this suggestion ends up being wontfix we can always close this issue out, however I didn't want it to get lost given that the PR was already merged :-)

> * We should loosen the trait restrictions on the Error for these closures except maybe for GenericErrorHandler.
> -- @hone

**Comment by Malax** [comment]
@hone I think this no longer relevant with the introduction of associated types in many places. I'll close this for now, feel free to re-open if you think there is still an issue.
