### ISSUE TITLE
CLI Binary for template generation

### ISSUE THREAD

**Issue by hone** [Malax/libcnb.rs#7]

**Comment by Malax** [comment]
See: https://github.com/Malax/rust-cnb-starter

**Comment by Malax** [comment]
@hone I don't think we need this anymore with #199 which makes most of the project boilerplate obsolete. Thoughts? cc: @edmorley

**Comment by edmorley** [comment]
Yeah I think between now having `cargo libcnb package`, the new `Layer` API being simpler, and having things like the `buildpack_main!` macro, there is a lot less to set up/understand when creating a new buildpack. In addition we have the hello world example buildpack people could just copy.

**Comment by Malax** [comment]
I'll close this for now, we can always reopen :)

**Comment by hone** [comment]
@Malax I actually would still like something in `carge libcnb package` like `rails new` or a template unless we want to defer to `pack` for `buildpack.toml` generation etc.

**Comment by hone** [comment]
Another option would to move this work upstream that would time into [RFC#77](https://github.com/buildpacks/rfcs/blob/main/text/0077-pack-buildpack-create.md).
