### ISSUE TITLE
libcnb-data

### ISSUE THREAD

**Issue by hone** [Malax/libcnb.rs#81]
I'd like to use the data structures of libcnb independent of the rest of the library. Thoughts on splitting this apart?

**Comment by edmorley** [comment]
@hone What's the use-case out of curiosity?

If we were to split this, I have a strong preference to keeping it in this repo and using cargo workspaces, rather than creating another repo.

**Comment by hone** [comment]
> @hone What's the use-case out of curiosity?

I'm spiking out out a launcher in rust and need to process `launch.toml`. It seems silly that I'd have to rewrite the same data structures. @Malax and I intended for these data structures to enforce the spec. I'm not writing a buildpack 

I think step 1 is to make everything in `src/data` implement `Serialize/Deserialize` see #82.

There's a common pattern for "-sys" crates to be nested like https://github.com/tildeio/helix/tree/master/crates/libcruby-sys. Maybe we could call it `libcnb-sys` instead?

**Comment by Malax** [comment]
I think we could also go one step further and strictly split the code that implements the spec (mostly TOML file structure, validation) and the framework that adds high-level facilities to make writing a buildpack convenient.

`libcnb` seems the to be the perfect name for the low-level spec stuff and the framework would need another name. That `libcnb` would be unopinionated, have nothing that's not in the spec. Both crates could live in the same repo to make it easier to maintain both.
