### ISSUE TITLE
name required by BuildpackToml

### ISSUE THREAD

**Issue by hone** [Malax/libcnb.rs#91]
Ran into this while helping @lillianzhang331run through the [buildpack author guide](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/). There is an error with the `name` field missing from the `buildpack` key. The spec isn't always clear, but I'm pretty sure `buildpack.name` is optional. This breaks both `bin/detect` and `bin/build` with a TOML deserialization error. Errors occurring during `bin/detect` just look like failed detection which can be hard to debug.

**Comment by lillianzhang331** [comment]
The error I got was under the build step: 

> Cannot read buildpack descriptor (buildpack.toml): TOML deserialization error while reading TOML file: missing field `name` for key `buildpack`

Was only able to surface this error after changing the generated `bin/detect` code under `target/buildpack` to bash.

**Comment by edmorley** [comment]
> Errors occurring during `bin/detect` just look like failed detection which can be hard to debug.

I wonder if we should ask upstream to output stderr iff detect exits abnormally (non-zero and non-100)? Currently verbose mode has to be used to see the actual error message iirc.

**Comment by hone** [comment]
I believe this is up to the platform. Do you want to file something on pack?

**Comment by hone** [comment]
Filed https://github.com/buildpacks/pack/issues/1292

**Comment by edmorley** [comment]
Thank you :-)
